const languageColors = [
  "#3498db", // Blue
  "#e74c3c", // Red
  "#2ecc71", // Green
  "#9b59b6", // Purple
  "#f39c12", // Orange
  "#1abc9c", // Turquoise
  "#e67e22", // Brown
  "#6a1b9a", // Dark Purple
  "#d35400", // Rust
  "#27ae60", // Forest Green
  "#8e44ad", // Violet
  "#c0392b", // Dark Red
  "#16a085", // Dark Cyan
  "#f1c40f", // Yellow
  "#34495e", // Midnight Blue
];

const regionData = [
    {
      "region": "CAR",
      "short-info": "Cordillera Administrative Region jaan ako nag aaral madami bondok jan",
      "population": 7.7,
      "land-area": "12,000",
      "languages-spoken": "Tagalog, Kapampangan, Pangasinan",
      "population-distribution": "Tagalog: 70%, Kapampangan: 20%, Pangasinan: 10%",
      "major-dialects": "Tagalog",
      "language-resources": "www.docs.google.com"
    },
    {
      "region": "NCR",
      "short-info": "jan sa manila pangit jan maosok",
      "population": 15,
      "land-area": "14,000",
      "languages-spoken": "Tagalog, Bicolano, English",
      "population-distribution": "Tagalog: 80%, Bicolano: 15%, English: 5%",
      "major-dialects": "Tagalog",
      "language-resources": "www.slu.edu.ph"
    },
    {
      "region": "ARMM",
      "short-info": "mmmmm sarap",
      "population": 3.2,
      "land-area": "16,000",
      "languages-spoken": "Tagalog, Mindoro languages, English",
      "population-distribution": "Tagalog: 75%, Mindoro languages: 20%, English: 5%",
      "major-dialects": "Tagalog",
      "language-resources": "www.baguiocity.com"
    },
    {
      "region": "Region-I",
      "short-info": "Northwestern tip of Luzon, known for beaches and windsurfing",
      "population": 5.3,
      "land-area": "13,851",
      "languages-spoken": "Ilocano, Tagalog, Pangasinan",
      "population-distribution": "Ilocano: 85%, Tagalog: 10%, Pangasinan: 5%",
      "major-dialects": "Ilocano",
      "language-resources": "www.github.com"
    },
    {
      "region": "Region-II",
      "short-info": "Cagayan Valley, known for its rice terraces and waterfalls",
      "population": 3.2,
      "land-area": "26,846",
      "languages-spoken": "Tagalog, Ilocano, Ibanag",
      "population-distribution": "Tagalog: 55%, Ilocano: 30%, Ibanag: 15%",
      "major-dialects": "Ilocano",
      "language-resources": "www.slu.edu.ph"
    },
    {
      "region": "Region-III",
      "short-info": "Central Luzon, known for its volcanoes and hot springs",
      "population": 12.3,
      "land-area": "39,706",
      "languages-spoken": "Tagalog, Kapampangan, Pangasinan",
      "population-distribution": "Tagalog: 70%, Kapampangan: 20%, Pangasinan: 10%",
      "major-dialects": "Tagalog",
      "language-resources": "www.fb.com"
    },
    {
      "region": "Region-IVA",
      "short-info": "CALABARZON, known for its beaches, mountains, and industrial parks",
      "population": 15.4,
      "land-area": "14,230",
      "languages-spoken": "Tagalog, Bicolano, English",
      "population-distribution": "Tagalog: 80%, Bicolano: 15%, English: 5%",
      "major-dialects": "Tagalog",
      "language-resources": "www.instagram.com"
    },
    {
      "region": "Region-IVB",
      "short-info": "MIMAROPA, known for its islands, beaches, and marine life",
      "population": 3.1,
      "land-area": "13,328",
      "languages-spoken": "Tagalog, Mindoro languages, English",
      "population-distribution": "Tagalog: 75%, Mindoro languages: 20%, English: 5%",
      "major-dialects": "Tagalog",
      "language-resources": "www.tiktok.com"
    },
    {
      "region": "Region-V",
      "short-info": "Southern part of Luzon, known for Mayon Volcano and Bicolano cuisine",
      "population": 6.7,
      "land-area": "9,575",
      "languages-spoken": "Bicolano, Tagalog, English",
      "population-distribution": "Bicolano: 80%, Tagalog: 15%, English: 5%",
      "major-dialects": "Bicolano",
      "language-resources": "www.pakyu.com"
    },
    {
      "region": "Region-VI",
      "short-info": "Panay Island and surrounding islands, known for sugar production and beaches",
      "population": 7.5,
      "land-area": "20,760",
      "languages-spoken": "Hiligaynon, Cebuano, Tagalog",
      "population-distribution": "Hiligaynon: 65%, Cebuano: 20%, Tagalog: 15%",
      "major-dialects": "Kapampangan",
      "language-resources": "www.bicolexpress.com"
    },
    {
      "region": "Region-VII",
      "short-info": "Cebu Island and Bohol Island, known for chocolate production and diving",
      "population": 5.1,
      "land-area": "14,849",
      "languages-spoken": "Cebuano, Tagalog, English",
      "population-distribution": "Cebuano: 85%, Tagalog: 10%, English: 5%",
      "major-dialects": "Kapampangan",
      "language-resources": "www.instagram.com"
    },
    {
      "region": "Region-VIII",
      "short-info": "Leyte Island and Samar Island, known for its historical sites and natural beauty",
      "population": 4.2,
      "land-area": "23,142",
      "languages-spoken": "Cebuano, Waray, Tagalog",
      "population-distribution": "Cebuano: 50%, Waray:50%",
      "major-dialects": "Caviteno",
      "language-resources": "www.tiktok.com"
    },
    {
      "region": "Region-IX",
      "short-info": "cloud nine",
      "population": 4.4,
      "land-area": "12,123",
      "languages-spoken": "Tagalog, Kapampangan, Pangasinan",
      "population-distribution": "Ilocano: 85%, Tagalog: 10%, Pangasinan: 5%",
      "major-dialects": "Ilocano",
      "language-resources": "www.instagram.com"
    },
    {
      "region": "Region-X",
      "short-info": "x-men",
      "population": 6,
      "land-area": "132,233",
      "languages-spoken": "Tagalog, Bicolano, English",
      "population-distribution": "Tagalog: 55%, Ilocano: 30%, Ibanag: 15%",
      "major-dialects": "Ilocano",
      "language-resources": "www.tiktok.com"
    },
    {
      "region": "Region-XI",
      "short-info": "seven eleven",
      "population": 7,
      "land-area": "21,677",
      "languages-spoken": "Tagalog, Mindoro languages, English",
      "population-distribution": "Tagalog: 70%, Kapampangan: 20%, Pangasinan: 10%",
      "major-dialects": "Tagalog",
      "language-resources": "www.instagram.com"
    },
    {
      "region": "Region-XII",
      "short-info": "eyyy",
      "population": 8,
      "land-area": "11,111",
      "languages-spoken": "Hiligaynon, Cebuano, Tagalog",
      "population-distribution": "Tagalog: 75%, Mindoro languages: 20%, English: 5%",
      "major-dialects": "Tagalog",
      "language-resources": "www.tiktok.com"
    },
    {
      "region": "Region-XIII",
      "short-info": "This is the region where they call \"Region Thirteen",
      "population": 5.5,
      "land-area": "90,123",
      "languages-spoken": "Cebuano, Waray, Tagalog",
      "population-distribution": "Cebuano: 85%, Tagalog: 10%, English: 5%",
      "major-dialects": "Bicolano",
      "language-resources": "www.sanmiguel.com"
    }
  ]


provinceData = [
  {
    "region": "CAR",
    "province": "Abra",
    "capital": "Abra City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 5.4,
    "land-area": "180,141",
    "popular-literature": "Ibong Adarna",
    "lit-address": "2 E 55th St Unit 803",
    "languages": "Tagalog, Kapampangan, Pangasinan",
    "population-distribution": "Tagalog: 70%, Kapampangan: 20%, Pangasinan: 10%",
    "image": ""
  },
  {
    "region": "CAR",
    "province": "Apayao",
    "capital": "Apayao City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 4.3,
    "land-area": "118,961",
    "popular-literature": "Alim at Hudhud",
    "lit-address": "Central Park Tower Penthouse-217 W 57th New York St Unit Penthouse",
    "languages": "Tagalog, Bicolano, English",
    "population-distribution": "Tagalog: 80%, Bicolano: 15%, English: 5%",
    "image": ""
  },
  {
    "region": "CAR",
    "province": "Benguet",
    "capital": "La Trinidad",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 3.9,
    "land-area": "755,459",
    "popular-literature": "Awan watwat mi",
    "lit-address": "620 Sinclair Ave",
    "languages": "Tagalog, Mindoro languages, English",
    "population-distribution": "Tagalog: 75%, Mindoro languages: 20%, English: 5%",
    "image": ""
  },
  {
    "region": "CAR",
    "province": "Ifugao",
    "capital": "Lagawe",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 8,
    "land-area": "542,103",
    "popular-literature": "Ibong Adarna",
    "lit-address": "2 E 55th St Unit 908W33",
    "languages": "Ilocano, Tagalog, Pangasinan",
    "population-distribution": "Ilocano: 85%, Tagalog: 10%, Pangasinan: 5%",
    "image": ""
  },
  {
    "region": "CAR",
    "province": "Kalinga",
    "capital": "Tabuk",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 5.2,
    "land-area": "655,491",
    "popular-literature": "Alim at Hudhud",
    "lit-address": "5 E 64th St",
    "languages": "Tagalog, Ilocano, Ibanag",
    "population-distribution": "Tagalog: 55%, Ilocano: 30%, Ibanag: 15%",
    "image": ""
  },
  {
    "region": "CAR",
    "province": "Mountain Province",
    "capital": "Mt. Province City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 2.1,
    "land-area": "288,023",
    "popular-literature": "Awan watwat mi",
    "lit-address": "584 Park Pl",
    "languages": "Tagalog, Kapampangan, Pangasinan",
    "population-distribution": "Tagalog: 70%, Kapampangan: 20%, Pangasinan: 10%",
    "image": ""
  },
  {
    "region": "NCR",
    "province": "Manila",
    "capital": "Manila City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 5,
    "land-area": "497,552",
    "popular-literature": "Ibong Adarna",
    "lit-address": "157 W 126th St Unit 1B",
    "languages": "Tagalog, Bicolano, English",
    "population-distribution": "Tagalog: 80%, Bicolano: 15%, English: 5%",
    "image": ""
  },
  {
    "region": "ARMM",
    "province": "Basilan",
    "capital": "Basilan City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 12,
    "land-area": "331,687",
    "popular-literature": "Alim at Hudhud",
    "lit-address": "177 Benedict Rd",
    "languages": "Tagalog, Mindoro languages, English",
    "population-distribution": "Tagalog: 75%, Mindoro languages: 20%, English: 5%",
    "image": ""
  },
  {
    "region": "ARMM",
    "province": "Cotabato",
    "capital": "Cotabato City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 15,
    "land-area": "90,336",
    "popular-literature": "Awan watwat mi",
    "lit-address": "875 Morrison Ave Apt 3M",
    "languages": "Bicolano, Tagalog, English",
    "population-distribution": "Bicolano: 80%, Tagalog: 15%, English: 5%",
    "image": ""
  },
  {
    "region": "ARMM",
    "province": "Lanao Del Sur",
    "capital": "Lanao Del Sur City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 3,
    "land-area": "151,025",
    "popular-literature": "Ibong Adarna",
    "lit-address": "1350 Ocean Pkwy Apt 5G",
    "languages": "Hiligaynon, Cebuano, Tagalog",
    "population-distribution": "Hiligaynon: 65%, Cebuano: 20%, Tagalog: 15%",
    "image": ""
  },
  {
    "region": "ARMM",
    "province": "Maguindanao",
    "capital": "Maguindanao City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 6,
    "land-area": "475,671",
    "popular-literature": "Alim at Hudhud",
    "lit-address": "800 Grand Concourse Apt 2JS",
    "languages": "Cebuano, Tagalog, English",
    "population-distribution": "Cebuano: 85%, Tagalog: 10%, English: 5%",
    "image": ""
  },
  {
    "region": "ARMM",
    "province": "Sulu",
    "capital": "Sulu City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 14,
    "land-area": "87,175",
    "popular-literature": "Awan watwat mi",
    "lit-address": "456 Van Name Ave",
    "languages": "Cebuano, Waray, Tagalog",
    "population-distribution": "Cebuano: 50%, Waray:50%",
    "image": ""
  },
  {
    "region": "ARMM",
    "province": "Tawi Tawi",
    "capital": "Tawi-Tawi City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 12,
    "land-area": "431,635",
    "popular-literature": "Ibong Adarna",
    "lit-address": "34-41 85th St Unit 1D",
    "languages": "Tagalog, Kapampangan, Pangasinan",
    "population-distribution": "Ilocano: 85%, Tagalog: 10%, Pangasinan: 5%",
    "image": ""
  },
  {
    "region": "Region-I",
    "province": "Ilocos Norte",
    "capital": "Ilocos Norte City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 13,
    "land-area": "674,024",
    "popular-literature": "Alim at Hudhud",
    "lit-address": "91-15 Lamont Ave Unit 6D",
    "languages": "Tagalog, Bicolano, English",
    "population-distribution": "Tagalog: 55%, Ilocano: 30%, Ibanag: 15%",
    "image": ""
  },
  {
    "region": "Region-I",
    "province": "Ilocos Sur",
    "capital": "Ilocos Sur City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 15,
    "land-area": "488,415",
    "popular-literature": "Awan watwat mi",
    "lit-address": "61 Jane St Apt 6N",
    "languages": "Tagalog, Mindoro languages, English",
    "population-distribution": "Tagalog: 70%, Kapampangan: 20%, Pangasinan: 10%",
    "image": ""
  },
  {
    "region": "Region-I",
    "province": "La Union",
    "capital": "La Union City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 6,
    "land-area": "788,584",
    "popular-literature": "Ibong Adarna",
    "lit-address": "4654 Amboy Rd Unit 2B",
    "languages": "Hiligaynon, Cebuano, Tagalog",
    "population-distribution": "Tagalog: 75%, Mindoro languages: 20%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-I",
    "province": "Pangasinan",
    "capital": "Pangasinan City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 10,
    "land-area": "771,379",
    "popular-literature": "Alim at Hudhud",
    "lit-address": "28-31 Hobart St",
    "languages": "Cebuano, Waray, Tagalog",
    "population-distribution": "Cebuano: 85%, Tagalog: 10%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-II",
    "province": "Batanes",
    "capital": "Batanes City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 8,
    "land-area": "402,646",
    "popular-literature": "Awan watwat mi",
    "lit-address": "9430 Ridge Blvd Apt 6D",
    "languages": "Tagalog, Kapampangan, Pangasinan",
    "population-distribution": "Tagalog: 70%, Kapampangan: 20%, Pangasinan: 10%",
    "image": ""
  },
  {
    "region": "Region-II",
    "province": "Cagayan",
    "capital": "Cagayan City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 3,
    "land-area": "379,042",
    "popular-literature": "Ibong Adarna",
    "lit-address": "5800 Arlington Ave Apt 21A",
    "languages": "Tagalog, Bicolano, English",
    "population-distribution": "Tagalog: 80%, Bicolano: 15%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-II",
    "province": "Isabela",
    "capital": "Isabela City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 10,
    "land-area": "817,349",
    "popular-literature": "Alim at Hudhud",
    "lit-address": "92-29 Queens Blvd Unit 3H",
    "languages": "Tagalog, Mindoro languages, English",
    "population-distribution": "Tagalog: 75%, Mindoro languages: 20%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-II",
    "province": "Nueva Vizcaya",
    "capital": "Nueva Vizcaya City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 12,
    "land-area": "804,204",
    "popular-literature": "Awan watwat mi",
    "lit-address": "27 Clove Way",
    "languages": "Ilocano, Tagalog, Pangasinan",
    "population-distribution": "Ilocano: 85%, Tagalog: 10%, Pangasinan: 5%",
    "image": ""
  },
  {
    "region": "Region-II",
    "province": "Quirino",
    "capital": "Quirino City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 8,
    "land-area": "397,336",
    "popular-literature": "Ibong Adarna",
    "lit-address": "10724 71st Rd Apt 9F",
    "languages": "Tagalog, Ilocano, Ibanag",
    "population-distribution": "Tagalog: 55%, Ilocano: 30%, Ibanag: 15%",
    "image": ""
  },
  {
    "region": "Region-III",
    "province": "Aurora",
    "capital": "Aurora City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 7,
    "land-area": "844,495",
    "popular-literature": "Alim at Hudhud",
    "lit-address": "1038 Throggs Neck Expy Unit Sr",
    "languages": "Tagalog, Kapampangan, Pangasinan",
    "population-distribution": "Tagalog: 70%, Kapampangan: 20%, Pangasinan: 10%",
    "image": ""
  },
  {
    "region": "Region-III",
    "province": "Bataan",
    "capital": "Bataan City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 6,
    "land-area": "897,656",
    "popular-literature": "Awan watwat mi",
    "lit-address": "165 Cromwell Ave Apt 2B",
    "languages": "Tagalog, Bicolano, English",
    "population-distribution": "Tagalog: 80%, Bicolano: 15%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-III",
    "province": "Bulacan",
    "capital": "Bulacan City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 8,
    "land-area": "743,508",
    "popular-literature": "Ibong Adarna",
    "lit-address": "280 Loretto St",
    "languages": "Tagalog, Mindoro languages, English",
    "population-distribution": "Tagalog: 75%, Mindoro languages: 20%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-III",
    "province": "Nueva Ecija",
    "capital": "Nueva Ecija City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 12,
    "land-area": "785,469",
    "popular-literature": "Alim at Hudhud",
    "lit-address": "149-07 85 Rd",
    "languages": "Bicolano, Tagalog, English",
    "population-distribution": "Bicolano: 80%, Tagalog: 15%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-III",
    "province": "Pampanga",
    "capital": "Pampanga City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 14,
    "land-area": "552,643",
    "popular-literature": "Awan watwat mi",
    "lit-address": "35-45 81st St Unit E1",
    "languages": "Hiligaynon, Cebuano, Tagalog",
    "population-distribution": "Hiligaynon: 65%, Cebuano: 20%, Tagalog: 15%",
    "image": ""
  },
  {
    "region": "Region-III",
    "province": "Tarlac",
    "capital": "Tarlac City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 6,
    "land-area": "112,504",
    "popular-literature": "Ibong Adarna",
    "lit-address": "2361 81st St",
    "languages": "Cebuano, Tagalog, English",
    "population-distribution": "Cebuano: 85%, Tagalog: 10%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-III",
    "province": "Zambales",
    "capital": "Zambales City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 7,
    "land-area": "568,600",
    "popular-literature": "Alim at Hudhud",
    "lit-address": "33-24 Junction Blvd Unit 6R",
    "languages": "Cebuano, Waray, Tagalog",
    "population-distribution": "Cebuano: 50%, Waray:50%",
    "image": ""
  },
  {
    "region": "Region-IVA",
    "province": "Batangas",
    "capital": "Batangas City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 3,
    "land-area": "513,593",
    "popular-literature": "Awan watwat mi",
    "lit-address": "310-312 Hillside Ave",
    "languages": "Tagalog, Kapampangan, Pangasinan",
    "population-distribution": "Ilocano: 85%, Tagalog: 10%, Pangasinan: 5%",
    "image": ""
  },
  {
    "region": "Region-IVA",
    "province": "Cavite",
    "capital": "Cavite City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 13,
    "land-area": "96,416",
    "popular-literature": "Ibong Adarna",
    "lit-address": "543 Hollywood Ave",
    "languages": "Tagalog, Bicolano, English",
    "population-distribution": "Tagalog: 55%, Ilocano: 30%, Ibanag: 15%",
    "image": ""
  },
  {
    "region": "Region-IVA",
    "province": "Laguna",
    "capital": "Laguna City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 5,
    "land-area": "708,706",
    "popular-literature": "Alim at Hudhud",
    "lit-address": "47 Lynn Ct",
    "languages": "Tagalog, Mindoro languages, English",
    "population-distribution": "Tagalog: 70%, Kapampangan: 20%, Pangasinan: 10%",
    "image": ""
  },
  {
    "region": "Region-IVA",
    "province": "Quezon",
    "capital": "Quezon City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 12,
    "land-area": "466,954",
    "popular-literature": "Awan watwat mi",
    "lit-address": "366 Union Ave Unit 4",
    "languages": "Hiligaynon, Cebuano, Tagalog",
    "population-distribution": "Tagalog: 75%, Mindoro languages: 20%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-IVA",
    "province": "Rizal",
    "capital": "Rizal City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 5,
    "land-area": "521,097",
    "popular-literature": "Ibong Adarna",
    "lit-address": "544 Hinsdale St",
    "languages": "Cebuano, Waray, Tagalog",
    "population-distribution": "Cebuano: 85%, Tagalog: 10%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-IVB",
    "province": "Marinduque",
    "capital": "Marinduque City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 11,
    "land-area": "232,363",
    "popular-literature": "Alim at Hudhud",
    "lit-address": "1801 Ocean Ave Apt 4A",
    "languages": "Tagalog, Kapampangan, Pangasinan",
    "population-distribution": "Tagalog: 70%, Kapampangan: 20%, Pangasinan: 10%",
    "image": ""
  },
  {
    "region": "Region-IVB",
    "province": "Mindoro Occidental",
    "capital": "Mindoro Occidental City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 3,
    "land-area": "864,129",
    "popular-literature": "Awan watwat mi",
    "lit-address": "1238 63rd St Unit 432",
    "languages": "Tagalog, Bicolano, English",
    "population-distribution": "Tagalog: 80%, Bicolano: 15%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-IVB",
    "province": "Mindoro Oriental",
    "capital": "Mindoro Oriental City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 8,
    "land-area": "269,406",
    "popular-literature": "Ibong Adarna",
    "lit-address": "310-312 Hillside Ave",
    "languages": "Tagalog, Mindoro languages, English",
    "population-distribution": "Tagalog: 75%, Mindoro languages: 20%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-IVB",
    "province": "Palawan",
    "capital": "Palawan City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 12,
    "land-area": "174,304",
    "popular-literature": "Alim at Hudhud",
    "lit-address": "44-55 Kissena Blvd Unit 5F",
    "languages": "Ilocano, Tagalog, Pangasinan",
    "population-distribution": "Ilocano: 85%, Tagalog: 10%, Pangasinan: 5%",
    "image": ""
  },
  {
    "region": "Region-IVB",
    "province": "Romblon",
    "capital": "Romblon City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 4,
    "land-area": "837,275",
    "popular-literature": "Awan watwat mi",
    "lit-address": "338 Berry St Apt 4E",
    "languages": "Tagalog, Ilocano, Ibanag",
    "population-distribution": "Tagalog: 55%, Ilocano: 30%, Ibanag: 15%",
    "image": ""
  },
  {
    "region": "Region-V",
    "province": "Albay",
    "capital": "Albay City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 9,
    "land-area": "154,324",
    "popular-literature": "Ibong Adarna",
    "lit-address": "10 Simon Ct",
    "languages": "Tagalog, Kapampangan, Pangasinan",
    "population-distribution": "Tagalog: 70%, Kapampangan: 20%, Pangasinan: 10%",
    "image": ""
  },
  {
    "region": "Region-V",
    "province": "Camarines Norte",
    "capital": "Camarines Norte City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 8,
    "land-area": "902,015",
    "popular-literature": "Alim at Hudhud",
    "lit-address": "229 W Tremont Ave Unit A",
    "languages": "Tagalog, Bicolano, English",
    "population-distribution": "Tagalog: 80%, Bicolano: 15%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-V",
    "province": "Camarines Sur",
    "capital": "Camarines Sur City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 8,
    "land-area": "647,446",
    "popular-literature": "Awan watwat mi",
    "lit-address": "2226 63rd St",
    "languages": "Tagalog, Mindoro languages, English",
    "population-distribution": "Tagalog: 75%, Mindoro languages: 20%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-V",
    "province": "Catanduanes",
    "capital": "Catanduanes City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 6,
    "land-area": "619,794",
    "popular-literature": "Ibong Adarna",
    "lit-address": "86-05 91st Ave",
    "languages": "Bicolano, Tagalog, English",
    "population-distribution": "Bicolano: 80%, Tagalog: 15%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-V",
    "province": "Masbate",
    "capital": "Masbate City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 13,
    "land-area": "174,200",
    "popular-literature": "Alim at Hudhud",
    "lit-address": "828 Gerard Ave Apt 5F",
    "languages": "Hiligaynon, Cebuano, Tagalog",
    "population-distribution": "Hiligaynon: 65%, Cebuano: 20%, Tagalog: 15%",
    "image": ""
  },
  {
    "region": "Region-V",
    "province": "Sorsogon",
    "capital": "Sorsogon City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 6,
    "land-area": "696,474",
    "popular-literature": "Awan watwat mi",
    "lit-address": "43-40 Union St Unit 3D",
    "languages": "Cebuano, Tagalog, English",
    "population-distribution": "Cebuano: 85%, Tagalog: 10%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-VI",
    "province": "Aklan",
    "capital": "Aklan City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 8,
    "land-area": "564,030",
    "popular-literature": "Ibong Adarna",
    "lit-address": "111-31 141st St",
    "languages": "Cebuano, Waray, Tagalog",
    "population-distribution": "Cebuano: 50%, Waray:50%",
    "image": ""
  },
  {
    "region": "Region-VI",
    "province": "Antique",
    "capital": "Antique City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 12,
    "land-area": "994,350",
    "popular-literature": "Alim at Hudhud",
    "lit-address": "123 Prince St Unit 1",
    "languages": "Tagalog, Kapampangan, Pangasinan",
    "population-distribution": "Ilocano: 85%, Tagalog: 10%, Pangasinan: 5%",
    "image": ""
  },
  {
    "region": "Region-VI",
    "province": "Capiz",
    "capital": "Capiz City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 8,
    "land-area": "843,543",
    "popular-literature": "Awan watwat mi",
    "lit-address": "32-39 Jordan St",
    "languages": "Tagalog, Bicolano, English",
    "population-distribution": "Tagalog: 55%, Ilocano: 30%, Ibanag: 15%",
    "image": ""
  },
  {
    "region": "Region-VI",
    "province": "Guimaras",
    "capital": "Guimaras City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 9,
    "land-area": "361,227",
    "popular-literature": "Ibong Adarna",
    "lit-address": "55 Austin Pl Apt 4L",
    "languages": "Tagalog, Mindoro languages, English",
    "population-distribution": "Tagalog: 70%, Kapampangan: 20%, Pangasinan: 10%",
    "image": ""
  },
  {
    "region": "Region-VI",
    "province": "Iloilo",
    "capital": "Iloilo City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 8,
    "land-area": "718,920",
    "popular-literature": "Alim at Hudhud",
    "lit-address": "17 S Greenleaf Ave",
    "languages": "Hiligaynon, Cebuano, Tagalog",
    "population-distribution": "Tagalog: 75%, Mindoro languages: 20%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-VI",
    "province": "Negros Occidental",
    "capital": "Negros Occidental City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 2,
    "land-area": "262,453",
    "popular-literature": "Awan watwat mi",
    "lit-address": "101-55 112th St",
    "languages": "Cebuano, Waray, Tagalog",
    "population-distribution": "Cebuano: 85%, Tagalog: 10%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-VII",
    "province": "Bohol",
    "capital": "Bohol City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 4,
    "land-area": "103,142",
    "popular-literature": "Ibong Adarna",
    "lit-address": "66 Bay 22nd St",
    "languages": "Tagalog, Kapampangan, Pangasinan",
    "population-distribution": "Tagalog: 70%, Kapampangan: 20%, Pangasinan: 10%",
    "image": ""
  },
  {
    "region": "Region-VII",
    "province": "Cebu",
    "capital": "Cebu City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 8,
    "land-area": "817,941",
    "popular-literature": "Alim at Hudhud",
    "lit-address": "350 Richmond Ter Apt 3M",
    "languages": "Tagalog, Bicolano, English",
    "population-distribution": "Tagalog: 80%, Bicolano: 15%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-VII",
    "province": "Negros Oriental",
    "capital": "Negros Oriental City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 8,
    "land-area": "687,932",
    "popular-literature": "Awan watwat mi",
    "lit-address": "259 80th St",
    "languages": "Tagalog, Mindoro languages, English",
    "population-distribution": "Tagalog: 75%, Mindoro languages: 20%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-VII",
    "province": "Siquijor",
    "capital": "Siquijor City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 14,
    "land-area": "451,184",
    "popular-literature": "Ibong Adarna",
    "lit-address": "240 Centre St Unit 2M",
    "languages": "Ilocano, Tagalog, Pangasinan",
    "population-distribution": "Ilocano: 85%, Tagalog: 10%, Pangasinan: 5%",
    "image": ""
  },
  {
    "region": "Region-VIII",
    "province": "Biliran",
    "capital": "Biliran City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 5,
    "land-area": "990,787",
    "popular-literature": "Alim at Hudhud",
    "lit-address": "473 Hicks St Apt 4",
    "languages": "Tagalog, Ilocano, Ibanag",
    "population-distribution": "Tagalog: 55%, Ilocano: 30%, Ibanag: 15%",
    "image": ""
  },
  {
    "region": "Region-VIII",
    "province": "Eastern Samar",
    "capital": "Eastern Samar City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 15,
    "land-area": "552,674",
    "popular-literature": "Awan watwat mi",
    "lit-address": "342 Manhattan St",
    "languages": "Tagalog, Kapampangan, Pangasinan",
    "population-distribution": "Tagalog: 70%, Kapampangan: 20%, Pangasinan: 10%",
    "image": ""
  },
  {
    "region": "Region-VIII",
    "province": "Leyte",
    "capital": "Leyte City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 5,
    "land-area": "747,885",
    "popular-literature": "Ibong Adarna",
    "lit-address": "1191 Clove Rd",
    "languages": "Tagalog, Bicolano, English",
    "population-distribution": "Tagalog: 80%, Bicolano: 15%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-VIII",
    "province": "Northern Samar",
    "capital": "Northern Samar City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 15,
    "land-area": "130,747",
    "popular-literature": "Alim at Hudhud",
    "lit-address": "Waldron Ave",
    "languages": "Tagalog, Mindoro languages, English",
    "population-distribution": "Tagalog: 75%, Mindoro languages: 20%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-VIII",
    "province": "Samar",
    "capital": "Samar City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 15,
    "land-area": "273,665",
    "popular-literature": "Awan watwat mi",
    "lit-address": "184 Lincoln Pl Unit 2",
    "languages": "Bicolano, Tagalog, English",
    "population-distribution": "Bicolano: 80%, Tagalog: 15%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-VIII",
    "province": "Southern Leyte",
    "capital": "Southern Leyte City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 7,
    "land-area": "467,942",
    "popular-literature": "Ibong Adarna",
    "lit-address": "263 W End Ave Apt 14C",
    "languages": "Hiligaynon, Cebuano, Tagalog",
    "population-distribution": "Hiligaynon: 65%, Cebuano: 20%, Tagalog: 15%",
    "image": ""
  },
  {
    "region": "Region-IX",
    "province": "Zamboanga",
    "capital": "Zamboanga City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 2,
    "land-area": "925,914",
    "popular-literature": "Alim at Hudhud",
    "lit-address": "50 Brighton 1 Rd Unit 5H",
    "languages": "Cebuano, Tagalog, English",
    "population-distribution": "Cebuano: 85%, Tagalog: 10%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-IX",
    "province": "Zamboanga Del Norte",
    "capital": "Zamboanga Del Norte City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 6,
    "land-area": "372,161",
    "popular-literature": "Awan watwat mi",
    "lit-address": "333 E 66th St Apt 8E",
    "languages": "Cebuano, Waray, Tagalog",
    "population-distribution": "Cebuano: 50%, Waray:50%",
    "image": ""
  },
  {
    "region": "Region-IX",
    "province": "Zamboanga Del Sur",
    "capital": "Zamboanga Del Sur City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 10,
    "land-area": "405,691",
    "popular-literature": "Ibong Adarna",
    "lit-address": "150 Rivington St Apt 3G",
    "languages": "Tagalog, Kapampangan, Pangasinan",
    "population-distribution": "Ilocano: 85%, Tagalog: 10%, Pangasinan: 5%",
    "image": ""
  },
  {
    "region": "Region-IX",
    "province": "Zamboanga Sibugay",
    "capital": "Zamboanga Sibugay City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 3,
    "land-area": "650,923",
    "popular-literature": "Alim at Hudhud",
    "lit-address": "1105 Cortelyou Rd # 301",
    "languages": "Tagalog, Bicolano, English",
    "population-distribution": "Tagalog: 55%, Ilocano: 30%, Ibanag: 15%",
    "image": ""
  },
  {
    "region": "Region-X",
    "province": "Bukidnon",
    "capital": "Bukidnon City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 5,
    "land-area": "672,397",
    "popular-literature": "Awan watwat mi",
    "lit-address": "737 Bergen St Apt 1B",
    "languages": "Tagalog, Mindoro languages, English",
    "population-distribution": "Tagalog: 70%, Kapampangan: 20%, Pangasinan: 10%",
    "image": ""
  },
  {
    "region": "Region-X",
    "province": "Camiguin",
    "capital": "Camiguin City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 13,
    "land-area": "612,571",
    "popular-literature": "Ibong Adarna",
    "lit-address": "83-55 Woodhaven Blvd Unit 1A",
    "languages": "Hiligaynon, Cebuano, Tagalog",
    "population-distribution": "Tagalog: 75%, Mindoro languages: 20%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-X",
    "province": "Lanao Del Norte",
    "capital": "Lanao Del Norte City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 2,
    "land-area": "774,830",
    "popular-literature": "Alim at Hudhud",
    "lit-address": "35 Center Pl",
    "languages": "Cebuano, Waray, Tagalog",
    "population-distribution": "Cebuano: 85%, Tagalog: 10%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-X",
    "province": "Misamis Occidental",
    "capital": "Misamis Occidental City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 12,
    "land-area": "994,296",
    "popular-literature": "Awan watwat mi",
    "lit-address": "205 Wiman Ave",
    "languages": "Tagalog, Kapampangan, Pangasinan",
    "population-distribution": "Tagalog: 70%, Kapampangan: 20%, Pangasinan: 10%",
    "image": ""
  },
  {
    "region": "Region-X",
    "province": "Misamis Oriental",
    "capital": "Misamis Oriental City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 3,
    "land-area": "107,047",
    "popular-literature": "Ibong Adarna",
    "lit-address": "4 E 79th St",
    "languages": "Tagalog, Bicolano, English",
    "population-distribution": "Tagalog: 80%, Bicolano: 15%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-XI",
    "province": "Compostela Valley",
    "capital": "Compostela Valley City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 9,
    "land-area": "369,220",
    "popular-literature": "Alim at Hudhud",
    "lit-address": "924 Lafayette Ave Unit Ph",
    "languages": "Tagalog, Mindoro languages, English",
    "population-distribution": "Tagalog: 75%, Mindoro languages: 20%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-XI",
    "province": "Davao Del Norte",
    "capital": "Davao Del Norte City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 4,
    "land-area": "406,887",
    "popular-literature": "Awan watwat mi",
    "lit-address": "1504 Jefferson Ave Unit Gardenb",
    "languages": "Ilocano, Tagalog, Pangasinan",
    "population-distribution": "Ilocano: 85%, Tagalog: 10%, Pangasinan: 5%",
    "image": ""
  },
  {
    "region": "Region-XI",
    "province": "Davao Del Sur",
    "capital": "Davao Del Sur City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 2,
    "land-area": "269,640",
    "popular-literature": "Ibong Adarna",
    "lit-address": "924 Lafayette Ave Apt 2",
    "languages": "Tagalog, Ilocano, Ibanag",
    "population-distribution": "Tagalog: 55%, Ilocano: 30%, Ibanag: 15%",
    "image": ""
  },
  {
    "region": "Region-XI",
    "province": "Davao Oriental",
    "capital": "Davao Oriental City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 13,
    "land-area": "322,650",
    "popular-literature": "Alim at Hudhud",
    "lit-address": "16-33 166th St",
    "languages": "Tagalog, Kapampangan, Pangasinan",
    "population-distribution": "Tagalog: 70%, Kapampangan: 20%, Pangasinan: 10%",
    "image": ""
  },
  {
    "region": "Region-XII",
    "province": "Cotabato",
    "capital": "Cotabato City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 10,
    "land-area": "433,935",
    "popular-literature": "Awan watwat mi",
    "lit-address": "425 Father Capodanno Blvd",
    "languages": "Tagalog, Bicolano, English",
    "population-distribution": "Tagalog: 80%, Bicolano: 15%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-XII",
    "province": "Sarangani",
    "capital": "Sarangani City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 5,
    "land-area": "348,192",
    "popular-literature": "Ibong Adarna",
    "lit-address": "519 Fairview Ave",
    "languages": "Tagalog, Mindoro languages, English",
    "population-distribution": "Tagalog: 75%, Mindoro languages: 20%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-XII",
    "province": "South Cotabato",
    "capital": "South Cotabato City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 3,
    "land-area": "158,923",
    "popular-literature": "Alim at Hudhud",
    "lit-address": "111 W 57th St # 50",
    "languages": "Bicolano, Tagalog, English",
    "population-distribution": "Bicolano: 80%, Tagalog: 15%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-XII",
    "province": "Sultan Kudarat",
    "capital": "Sultan Kudarat City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 10,
    "land-area": "595,526",
    "popular-literature": "Awan watwat mi",
    "lit-address": "234 Ocean View Ave",
    "languages": "Hiligaynon, Cebuano, Tagalog",
    "population-distribution": "Hiligaynon: 65%, Cebuano: 20%, Tagalog: 15%",
    "image": ""
  },
  {
    "region": "Region-XIII",
    "province": "Agusan Del Norte",
    "capital": "Agusan Del Norte City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 10,
    "land-area": "787,879",
    "popular-literature": "Ibong Adarna",
    "lit-address": "3652 DE Reimer Ave",
    "languages": "Cebuano, Tagalog, English",
    "population-distribution": "Cebuano: 85%, Tagalog: 10%, English: 5%",
    "image": ""
  },
  {
    "region": "Region-XIII",
    "province": "Agusan Del Sur",
    "capital": "Agusan Del Sur City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 4,
    "land-area": "860,318",
    "popular-literature": "Alim at Hudhud",
    "lit-address": "204-34 9th Ave",
    "languages": "Cebuano, Waray, Tagalog",
    "population-distribution": "Cebuano: 50%, Waray:50%",
    "image": ""
  },
  {
    "region": "Region-XIII",
    "province": "Surigao Del Norte",
    "capital": "Surigao Del Norte City",
    "short-info": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "population": 15,
    "land-area": "147,404",
    "popular-literature": "Awan watwat mi",
    "lit-address": "1383 Plimpton Ave Apt 1C",
    "languages": "Tagalog, Kapampangan, Pangasinan",
    "population-distribution": "Ilocano: 85%, Tagalog: 10%, Pangasinan: 5%",
    "image": ""
  },
  {
    "region": "Region-XIII",
    "province": "Surigao Del Sur",
    "capital": "Surigao Del Sur City",
    "short-info": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "population": 12,
    "land-area": "246,087",
    "popular-literature": "Ibong Adarna",
    "lit-address": "158-35 87th St",
    "languages": "Tagalog, Bicolano, English",
    "population-distribution": "Tagalog: 55%, Ilocano: 30%, Ibanag: 15%",
    "image": ""
  }
]